//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Jade.Model.MySql
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HFBBSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HFBBSEntities object using the connection string found in the 'HFBBSEntities' section of the application configuration file.
        /// </summary>
        public HFBBSEntities() : base("name=HFBBSEntities", "HFBBSEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HFBBSEntities object.
        /// </summary>
        public HFBBSEntities(string connectionString) : base(connectionString, "HFBBSEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HFBBSEntities object.
        /// </summary>
        public HFBBSEntities(EntityConnection connection) : base(connection, "HFBBSEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> user
        {
            get
            {
                if ((_user == null))
                {
                    _user = base.CreateObjectSet<user>("user");
                }
                return _user;
            }
        }
        private ObjectSet<user> _user;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<downloaddata> downloaddata
        {
            get
            {
                if ((_downloaddata == null))
                {
                    _downloaddata = base.CreateObjectSet<downloaddata>("downloaddata");
                }
                return _downloaddata;
            }
        }
        private ObjectSet<downloaddata> _downloaddata;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<imagefiles> imagefiles
        {
            get
            {
                if ((_imagefiles == null))
                {
                    _imagefiles = base.CreateObjectSet<imagefiles>("imagefiles");
                }
                return _imagefiles;
            }
        }
        private ObjectSet<imagefiles> _imagefiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userlog> userlog
        {
            get
            {
                if ((_userlog == null))
                {
                    _userlog = base.CreateObjectSet<userlog>("userlog");
                }
                return _userlog;
            }
        }
        private ObjectSet<userlog> _userlog;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser(user user)
        {
            base.AddObject("user", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the downloaddata EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodownloaddata(downloaddata downloaddata)
        {
            base.AddObject("downloaddata", downloaddata);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the imagefiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToimagefiles(imagefiles imagefiles)
        {
            base.AddObject("imagefiles", imagefiles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userlog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserlog(userlog userlog)
        {
            base.AddObject("userlog", userlog);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Jade.Model.MySql", Name="downloaddata")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class downloaddata : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new downloaddata object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cmspinglun">Initial value of the cmspinglun property.</param>
        /// <param name="bbspinglun">Initial value of the bbspinglun property.</param>
        /// <param name="iSkfbm">Initial value of the ISkfbm property.</param>
        /// <param name="iSgfbm">Initial value of the ISgfbm property.</param>
        /// <param name="isEdit">Initial value of the IsEdit property.</param>
        /// <param name="isDownload">Initial value of the IsDownload property.</param>
        /// <param name="isPublish">Initial value of the IsPublish property.</param>
        /// <param name="remoteId">Initial value of the RemoteId property.</param>
        public static downloaddata Createdownloaddata(global::System.Int32 id, global::System.Boolean cmspinglun, global::System.Boolean bbspinglun, global::System.Boolean iSkfbm, global::System.Boolean iSgfbm, global::System.Boolean isEdit, global::System.Boolean isDownload, global::System.Boolean isPublish, global::System.Int32 remoteId)
        {
            downloaddata downloaddata = new downloaddata();
            downloaddata.ID = id;
            downloaddata.cmspinglun = cmspinglun;
            downloaddata.bbspinglun = bbspinglun;
            downloaddata.ISkfbm = iSkfbm;
            downloaddata.ISgfbm = iSgfbm;
            downloaddata.IsEdit = isEdit;
            downloaddata.IsDownload = isDownload;
            downloaddata.IsPublish = isPublish;
            downloaddata.RemoteId = remoteId;
            return downloaddata;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TaskId
        {
            get
            {
                return _TaskId;
            }
            set
            {
                OnTaskIdChanging(value);
                ReportPropertyChanging("TaskId");
                _TaskId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaskId");
                OnTaskIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TaskId;
        partial void OnTaskIdChanging(Nullable<global::System.Int32> value);
        partial void OnTaskIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitle
        {
            get
            {
                return _SubTitle;
            }
            set
            {
                OnSubTitleChanging(value);
                ReportPropertyChanging("SubTitle");
                _SubTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitle");
                OnSubTitleChanged();
            }
        }
        private global::System.String _SubTitle;
        partial void OnSubTitleChanging(global::System.String value);
        partial void OnSubTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_source_name
        {
            get
            {
                return _news_source_name;
            }
            set
            {
                Onnews_source_nameChanging(value);
                ReportPropertyChanging("news_source_name");
                _news_source_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_source_name");
                Onnews_source_nameChanged();
            }
        }
        private global::System.String _news_source_name;
        partial void Onnews_source_nameChanging(global::System.String value);
        partial void Onnews_source_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_template_file
        {
            get
            {
                return _news_template_file;
            }
            set
            {
                Onnews_template_fileChanging(value);
                ReportPropertyChanging("news_template_file");
                _news_template_file = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_template_file");
                Onnews_template_fileChanged();
            }
        }
        private global::System.String _news_template_file;
        partial void Onnews_template_fileChanging(global::System.String value);
        partial void Onnews_template_fileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_top
        {
            get
            {
                return _news_top;
            }
            set
            {
                Onnews_topChanging(value);
                ReportPropertyChanging("news_top");
                _news_top = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_top");
                Onnews_topChanged();
            }
        }
        private global::System.String _news_top;
        partial void Onnews_topChanging(global::System.String value);
        partial void Onnews_topChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_guideimage
        {
            get
            {
                return _news_guideimage;
            }
            set
            {
                Onnews_guideimageChanging(value);
                ReportPropertyChanging("news_guideimage");
                _news_guideimage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_guideimage");
                Onnews_guideimageChanged();
            }
        }
        private global::System.String _news_guideimage;
        partial void Onnews_guideimageChanging(global::System.String value);
        partial void Onnews_guideimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_guideimage2
        {
            get
            {
                return _news_guideimage2;
            }
            set
            {
                Onnews_guideimage2Changing(value);
                ReportPropertyChanging("news_guideimage2");
                _news_guideimage2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_guideimage2");
                Onnews_guideimage2Changed();
            }
        }
        private global::System.String _news_guideimage2;
        partial void Onnews_guideimage2Changing(global::System.String value);
        partial void Onnews_guideimage2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_description
        {
            get
            {
                return _news_description;
            }
            set
            {
                Onnews_descriptionChanging(value);
                ReportPropertyChanging("news_description");
                _news_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_description");
                Onnews_descriptionChanged();
            }
        }
        private global::System.String _news_description;
        partial void Onnews_descriptionChanging(global::System.String value);
        partial void Onnews_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_link
        {
            get
            {
                return _news_link;
            }
            set
            {
                Onnews_linkChanging(value);
                ReportPropertyChanging("news_link");
                _news_link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_link");
                Onnews_linkChanged();
            }
        }
        private global::System.String _news_link;
        partial void Onnews_linkChanging(global::System.String value);
        partial void Onnews_linkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_down
        {
            get
            {
                return _news_down;
            }
            set
            {
                Onnews_downChanging(value);
                ReportPropertyChanging("news_down");
                _news_down = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_down");
                Onnews_downChanged();
            }
        }
        private global::System.String _news_down;
        partial void Onnews_downChanging(global::System.String value);
        partial void Onnews_downChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_right
        {
            get
            {
                return _news_right;
            }
            set
            {
                Onnews_rightChanging(value);
                ReportPropertyChanging("news_right");
                _news_right = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_right");
                Onnews_rightChanged();
            }
        }
        private global::System.String _news_right;
        partial void Onnews_rightChanging(global::System.String value);
        partial void Onnews_rightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_left
        {
            get
            {
                return _news_left;
            }
            set
            {
                Onnews_leftChanging(value);
                ReportPropertyChanging("news_left");
                _news_left = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_left");
                Onnews_leftChanged();
            }
        }
        private global::System.String _news_left;
        partial void Onnews_leftChanging(global::System.String value);
        partial void Onnews_leftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comment_url
        {
            get
            {
                return _comment_url;
            }
            set
            {
                Oncomment_urlChanging(value);
                ReportPropertyChanging("comment_url");
                _comment_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comment_url");
                Oncomment_urlChanged();
            }
        }
        private global::System.String _comment_url;
        partial void Oncomment_urlChanging(global::System.String value);
        partial void Oncomment_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_video
        {
            get
            {
                return _news_video;
            }
            set
            {
                Onnews_videoChanging(value);
                ReportPropertyChanging("news_video");
                _news_video = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_video");
                Onnews_videoChanged();
            }
        }
        private global::System.String _news_video;
        partial void Onnews_videoChanging(global::System.String value);
        partial void Onnews_videoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_keywords2
        {
            get
            {
                return _news_keywords2;
            }
            set
            {
                Onnews_keywords2Changing(value);
                ReportPropertyChanging("news_keywords2");
                _news_keywords2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_keywords2");
                Onnews_keywords2Changed();
            }
        }
        private global::System.String _news_keywords2;
        partial void Onnews_keywords2Changing(global::System.String value);
        partial void Onnews_keywords2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String label_base
        {
            get
            {
                return _label_base;
            }
            set
            {
                Onlabel_baseChanging(value);
                ReportPropertyChanging("label_base");
                _label_base = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("label_base");
                Onlabel_baseChanged();
            }
        }
        private global::System.String _label_base;
        partial void Onlabel_baseChanging(global::System.String value);
        partial void Onlabel_baseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean cmspinglun
        {
            get
            {
                return _cmspinglun;
            }
            set
            {
                OncmspinglunChanging(value);
                ReportPropertyChanging("cmspinglun");
                _cmspinglun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cmspinglun");
                OncmspinglunChanged();
            }
        }
        private global::System.Boolean _cmspinglun;
        partial void OncmspinglunChanging(global::System.Boolean value);
        partial void OncmspinglunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean bbspinglun
        {
            get
            {
                return _bbspinglun;
            }
            set
            {
                OnbbspinglunChanging(value);
                ReportPropertyChanging("bbspinglun");
                _bbspinglun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bbspinglun");
                OnbbspinglunChanged();
            }
        }
        private global::System.Boolean _bbspinglun;
        partial void OnbbspinglunChanging(global::System.Boolean value);
        partial void OnbbspinglunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ISkfbm
        {
            get
            {
                return _ISkfbm;
            }
            set
            {
                OnISkfbmChanging(value);
                ReportPropertyChanging("ISkfbm");
                _ISkfbm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISkfbm");
                OnISkfbmChanged();
            }
        }
        private global::System.Boolean _ISkfbm;
        partial void OnISkfbmChanging(global::System.Boolean value);
        partial void OnISkfbmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kfbm_id
        {
            get
            {
                return _kfbm_id;
            }
            set
            {
                Onkfbm_idChanging(value);
                ReportPropertyChanging("kfbm_id");
                _kfbm_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kfbm_id");
                Onkfbm_idChanged();
            }
        }
        private global::System.String _kfbm_id;
        partial void Onkfbm_idChanging(global::System.String value);
        partial void Onkfbm_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kfbm_link
        {
            get
            {
                return _kfbm_link;
            }
            set
            {
                Onkfbm_linkChanging(value);
                ReportPropertyChanging("kfbm_link");
                _kfbm_link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kfbm_link");
                Onkfbm_linkChanged();
            }
        }
        private global::System.String _kfbm_link;
        partial void Onkfbm_linkChanging(global::System.String value);
        partial void Onkfbm_linkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ISgfbm
        {
            get
            {
                return _ISgfbm;
            }
            set
            {
                OnISgfbmChanging(value);
                ReportPropertyChanging("ISgfbm");
                _ISgfbm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISgfbm");
                OnISgfbmChanged();
            }
        }
        private global::System.Boolean _ISgfbm;
        partial void OnISgfbmChanging(global::System.Boolean value);
        partial void OnISgfbmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gfbm_id
        {
            get
            {
                return _gfbm_id;
            }
            set
            {
                Ongfbm_idChanging(value);
                ReportPropertyChanging("gfbm_id");
                _gfbm_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gfbm_id");
                Ongfbm_idChanged();
            }
        }
        private global::System.String _gfbm_id;
        partial void Ongfbm_idChanging(global::System.String value);
        partial void Ongfbm_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gfbm_link
        {
            get
            {
                return _gfbm_link;
            }
            set
            {
                Ongfbm_linkChanging(value);
                ReportPropertyChanging("gfbm_link");
                _gfbm_link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gfbm_link");
                Ongfbm_linkChanged();
            }
        }
        private global::System.String _gfbm_link;
        partial void Ongfbm_linkChanging(global::System.String value);
        partial void Ongfbm_linkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String news_abs
        {
            get
            {
                return _news_abs;
            }
            set
            {
                Onnews_absChanging(value);
                ReportPropertyChanging("news_abs");
                _news_abs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("news_abs");
                Onnews_absChanged();
            }
        }
        private global::System.String _news_abs;
        partial void Onnews_absChanging(global::System.String value);
        partial void Onnews_absChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.String _CreateTime;
        partial void OnCreateTimeChanging(global::System.String value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Other
        {
            get
            {
                return _Other;
            }
            set
            {
                OnOtherChanging(value);
                ReportPropertyChanging("Other");
                _Other = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Other");
                OnOtherChanged();
            }
        }
        private global::System.String _Other;
        partial void OnOtherChanging(global::System.String value);
        partial void OnOtherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEdit
        {
            get
            {
                return _IsEdit;
            }
            set
            {
                OnIsEditChanging(value);
                ReportPropertyChanging("IsEdit");
                _IsEdit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEdit");
                OnIsEditChanged();
            }
        }
        private global::System.Boolean _IsEdit;
        partial void OnIsEditChanging(global::System.Boolean value);
        partial void OnIsEditChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EditorUserName
        {
            get
            {
                return _EditorUserName;
            }
            set
            {
                OnEditorUserNameChanging(value);
                ReportPropertyChanging("EditorUserName");
                _EditorUserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EditorUserName");
                OnEditorUserNameChanged();
            }
        }
        private global::System.String _EditorUserName;
        partial void OnEditorUserNameChanging(global::System.String value);
        partial void OnEditorUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DownloadTime
        {
            get
            {
                return _DownloadTime;
            }
            set
            {
                OnDownloadTimeChanging(value);
                ReportPropertyChanging("DownloadTime");
                _DownloadTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DownloadTime");
                OnDownloadTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DownloadTime;
        partial void OnDownloadTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDownloadTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDownload
        {
            get
            {
                return _IsDownload;
            }
            set
            {
                OnIsDownloadChanging(value);
                ReportPropertyChanging("IsDownload");
                _IsDownload = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDownload");
                OnIsDownloadChanged();
            }
        }
        private global::System.Boolean _IsDownload;
        partial void OnIsDownloadChanging(global::System.Boolean value);
        partial void OnIsDownloadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPublish
        {
            get
            {
                return _IsPublish;
            }
            set
            {
                OnIsPublishChanging(value);
                ReportPropertyChanging("IsPublish");
                _IsPublish = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPublish");
                OnIsPublishChanged();
            }
        }
        private global::System.Boolean _IsPublish;
        partial void OnIsPublishChanging(global::System.Boolean value);
        partial void OnIsPublishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EditTime
        {
            get
            {
                return _EditTime;
            }
            set
            {
                OnEditTimeChanging(value);
                ReportPropertyChanging("EditTime");
                _EditTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditTime");
                OnEditTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EditTime;
        partial void OnEditTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEditTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RemoteId
        {
            get
            {
                return _RemoteId;
            }
            set
            {
                OnRemoteIdChanging(value);
                ReportPropertyChanging("RemoteId");
                _RemoteId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RemoteId");
                OnRemoteIdChanged();
            }
        }
        private global::System.Int32 _RemoteId;
        partial void OnRemoteIdChanging(global::System.Int32 value);
        partial void OnRemoteIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Jade.Model.MySql", Name="imagefiles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class imagefiles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new imagefiles object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        public static imagefiles Createimagefiles(global::System.Int32 id, global::System.String fileName, global::System.String url)
        {
            imagefiles imagefiles = new imagefiles();
            imagefiles.Id = id;
            imagefiles.FileName = fileName;
            imagefiles.Url = url;
            return imagefiles;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Data
        {
            get
            {
                return StructuralObject.GetValidValue(_Data);
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.Byte[] _Data;
        partial void OnDataChanging(global::System.Byte[] value);
        partial void OnDataChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Jade.Model.MySql", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static user Createuser(global::System.Int32 userID)
        {
            user user = new user();
            user.UserID = userID;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsAdmin
        {
            get
            {
                return _IsAdmin;
            }
            set
            {
                OnIsAdminChanging(value);
                ReportPropertyChanging("IsAdmin");
                _IsAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdmin");
                OnIsAdminChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsAdmin;
        partial void OnIsAdminChanging(Nullable<global::System.Boolean> value);
        partial void OnIsAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Jade.Model.MySql", Name="userlog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userlog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userlog object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static userlog Createuserlog(global::System.Int32 id)
        {
            userlog userlog = new userlog();
            userlog.Id = id;
            return userlog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LogType
        {
            get
            {
                return _LogType;
            }
            set
            {
                OnLogTypeChanging(value);
                ReportPropertyChanging("LogType");
                _LogType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LogType");
                OnLogTypeChanged();
            }
        }
        private global::System.String _LogType;
        partial void OnLogTypeChanging(global::System.String value);
        partial void OnLogTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();

        #endregion
    
    }

    #endregion
    
}
